# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3d21d6259a7f59e8579df218ea14672af3295bca035236921aa0542a8806b989fcc28fd6dc5721c28c01b4bcf441b74a28cc02b71257e559b1a031a7a6f697b

test:
  secret_key_base: a26f5ff8dfbd32a8d3212d57824f6719a2343442701e40b160903b7c64167bef24d84430a69789b9b1ddc80e0a3478e741d1e994411c0770a3062bf68a62403c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
